import { CONTACTS } from './contacts.constants';

// Single source of truth for SEO / metadata. Set NEXT_PUBLIC_SITE_URL in the
// deploy environment to the real production domain.
export const SITE = {
  url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://vladimirh.dev',
  name: 'Vladimir Hlobchastyi',
  role: 'Senior Software Engineer (Product-Minded) · React, Next.js, Node.js & React Native',
  title: 'Vladimir Hlobchastyi — Senior Software Engineer (Product-Minded)',
  description:
    'Senior Software Engineer (Product-Minded) helping turn business rules into working web and mobile products with React, Next.js, Node.js, React Native, and TypeScript. Strong in frontend architecture, product flows, integrations, and release work.',
  locale: 'en_US',
  sameAs: [CONTACTS.linkedin.href, CONTACTS.github.href, CONTACTS.x.href, CONTACTS.telegram.href],
  keywords: [
    'Vladimir Hlobchastyi',
    'Software Engineer',
    'React Developer',
    'Next.js Developer',
    'Node.js Developer',
    'React Native Developer',
    'TypeScript Developer',
    'Ionic Developer',
    'Web Application Development',
    'Mobile App Development',
    'AI project analysis',
    'AI codebase audit',
    'AI codebase refactoring',
    'frontend architecture',
    'cross-platform delivery',
    'freelance React developer',
    'hire software engineer',
    'hire React Native developer',
    'JavaScript Engineer',
    'Frontend Engineer',
    'Senior Software Engineer',
    'Product-Minded Software Engineer',
  ],
  knowsAbout: [
    'React',
    'Next.js',
    'React Native',
    'Ionic',
    'TypeScript',
    'JavaScript',
    'Node.js',
    'GraphQL',
    'AI project analysis',
    'AI codebase recovery',
    'Frontend architecture',
    'WebRTC',
    'WebSockets',
    'Stripe',
    'Mapbox',
    'Tailwind CSS',
    'Web Application Development',
    'Mobile App Development',
  ],
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
    bing: process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION,
  },
} as const;
