import { CONTACTS } from './contacts';

// Single source of truth for SEO / metadata. Set NEXT_PUBLIC_SITE_URL in the
// deploy environment to the real production domain.
export const SITE = {
  url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://vladimirh.dev',
  name: 'Vladimir Hlobchastyi',
  role: 'Software Engineer · React, Next.js, Node.js & React Native',
  title: 'Vladimir Hlobchastyi — Software Engineer for Web, Mobile & AI Products',
  description:
    'Software Engineer building web, mobile and AI-powered products with React, Next.js, Node.js, React Native and TypeScript. Available for end-to-end product delivery, deployment, store release, refactoring and AI codebase rescue.',
  locale: 'en_US',
  sameAs: [CONTACTS.linkedin.href, CONTACTS.x.href, CONTACTS.telegram.href],
  keywords: [
    'Vladimir Hlobchastyi',
    'Software Engineer',
    'React Developer',
    'Next.js Developer',
    'Node.js Developer',
    'React Native Developer',
    'TypeScript Developer',
    'Ionic Developer',
    'Web Application Development',
    'Mobile App Development',
    'AI Systems',
    'AI project rescue',
    'backend development',
    'deployment',
    'App Store deployment',
    'Google Play deployment',
    'freelance React developer',
    'hire software engineer',
    'hire React Native developer',
    'JavaScript Engineer',
    'Frontend Engineer',
    'Backend Engineer',
  ],
  knowsAbout: [
    'React',
    'Next.js',
    'React Native',
    'Ionic',
    'TypeScript',
    'JavaScript',
    'Node.js',
    'GraphQL',
    'Backend architecture',
    'Deployment',
    'App Store release',
    'Google Play release',
    'WebRTC',
    'WebSockets',
    'Stripe',
    'Mapbox',
    'Tailwind CSS',
    'AI integration',
    'Frontend architecture',
    'Web Application Development',
    'Mobile App Development',
  ],
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
    bing: process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION,
  },
} as const;
